// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef ui_h
#define ui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
extern Fl_Group *stats;
#include <FL/Fl_Output.H>
extern Fl_Output *gs_today;
extern Fl_Output *gs_yesterday;
extern Fl_Output *gs_week;
extern Fl_Output *gs_alltime;
extern Fl_Group *keyboard;
#include <FL/Fl_Button.H>
extern Fl_Button *K_q;
extern Fl_Button *K_w;
extern Fl_Button *K_e;
extern Fl_Button *K_r;
extern Fl_Button *K_t;
extern Fl_Button *K_y;
extern Fl_Button *K_u;
extern Fl_Button *K_i;
extern Fl_Button *K_o;
extern Fl_Button *K_p;
extern Fl_Button *K_Lsqb;
extern Fl_Button *K_Rsbq;
extern Fl_Button *K_backsl;
extern Fl_Button *K_grave;
extern Fl_Button *K_one;
extern Fl_Button *K_two;
extern Fl_Button *K_three;
extern Fl_Button *K_four;
extern Fl_Button *K_five;
extern Fl_Button *K_six;
extern Fl_Button *K_seven;
extern Fl_Button *K_eight;
extern Fl_Button *K_nine;
extern Fl_Button *K_zero;
extern Fl_Button *K_minus;
extern Fl_Button *K_equals;
extern Fl_Button *K_tab;
extern Fl_Button *K_del;
extern Fl_Button *K_esc;
extern Fl_Button *K_f1;
extern Fl_Button *K_f2;
extern Fl_Button *K_f3;
extern Fl_Button *K_f4;
extern Fl_Button *K_f5;
extern Fl_Button *K_f6;
extern Fl_Button *K_f7;
extern Fl_Button *K_f8;
extern Fl_Button *K_f9;
extern Fl_Button *K_f10;
extern Fl_Button *K_f11;
extern Fl_Button *K_f12;
extern Fl_Button *K_caps;
extern Fl_Button *K_enter;
extern Fl_Button *K_a;
extern Fl_Button *K_s;
extern Fl_Button *K_d;
extern Fl_Button *K_f;
extern Fl_Button *K_g;
extern Fl_Button *K_h;
extern Fl_Button *K_j;
extern Fl_Button *K_k;
extern Fl_Button *K_l;
extern Fl_Button *K_semicolon;
extern Fl_Button *K_apostrophe;
extern Fl_Button *K_shiftL;
extern Fl_Button *K_shiftR;
extern Fl_Button *K_z;
extern Fl_Button *K_x;
extern Fl_Button *K_c;
extern Fl_Button *K_v;
extern Fl_Button *K_b;
extern Fl_Button *K_n;
extern Fl_Button *K_m;
extern Fl_Button *K_comma;
extern Fl_Button *K_dot;
extern Fl_Button *K_frontsl;
extern Fl_Button *K_ctrlL;
extern Fl_Button *K_alt1;
extern Fl_Button *K_cmdL;
extern Fl_Button *K_ctrlR;
extern Fl_Button *K_cmdR;
extern Fl_Button *K_fn;
extern Fl_Button *K_space;
extern Fl_Group *nav;
extern Fl_Button *nav_today;
extern Fl_Button *nav_yesterday;
extern Fl_Button *nav_week;
extern Fl_Button *nav_month;
extern Fl_Button *nav_sem;
extern Fl_Button *nav_year;
extern Fl_Button *nav_all;
#include <FL/Fl_Box.H>
extern Fl_Button *nav_more;
Fl_Double_Window* make_main_window();
#endif
